project:
  type: website
  output-dir: docs

website:
  title: "GDM 2025 Workshop"
  
  # Sidebar options
  
  sidebar:
    syle: "docked"
    search: true
    title: "GDM 2025 Workshop"
    contents:
      - text: Overview
        href: index.qmd
      - code-of-conduct.qmd
      - section: "Workshop material"
        contents:
          - text: "Session 1: Unix"
            href: https://docs.google.com/presentation/d/14wXx2teSk4jcvHENpN-TDYu1mMuBhmP47G6WzLNjTrg/edit?usp=sharing
          - text: "Session 2.1: Git"
            href: https://pawsey-internships.github.io/version-control/
          - text: "Session 2.2: Collaborative Git"
            href: https://docs.google.com/presentation/d/17v-ImCja0-Te8lyIOKQhzyOreQccb-2HqopUHnTfGEU/edit?usp=sharing
          - text: "Session 3: Intro to HPC"
            href: https://docs.google.com/presentation/d/1pu1PxsHo8dymT3Sz5njxHpWgcZAsYtYe/edit?usp=sharing&ouid=109436109386903974423&rtpof=true&sd=true
          - text: "Hackathon"
            href: session-hackathon.qmd
      - section: "Additional resources"
        contents:
          - setup.qmd
          - unix-shell.qmd
          - ssh.qmd
          - nano.qmd
          - vim.qmd
      - acknowledgements.qmd
  
  # Footer options
  
  page-footer: 
      right:
      - icon: github
        href: https://github.com/global-disease-modelling/2025-workshop
  
  # Appearance and misc.
  bread-crumbs: false
  page-navigation: true

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    toc: true
    code-overflow: wrap

execute:
  cache: true
  freeze: false
  
bibliography: references.bib
editor: visual
