project:
  type: website

website:
  title: "GDM Workshop 2025"
  navbar:
    page-navigation: true
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: code-of-conduct.qmd
        text: Code of Conduct
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-overflow: wrap

freeze: true
bibliography: references.bib
editor: visual
