project:
  type: website
  output-dir: docs

website:
  title: "GDM 2025 Workshop"
  
  # Sidebar options
  
  sidebar:
    syle: "docked"
    type: "dark"
    search: true
    title: "GDM 2025 Workshop"
    contents:
      - text: Overview
        href: index.qmd
      - code-of-conduct.qmd
      - section: "Workshop"
        contents:
          - session-1.qmd
          - session-2.qmd
          - session-3.qmd
      - section: "Resources"
        contents:
          - getting-started.qmd
          - collaborative-git.qmd
          - supercomputing.qmd
          - pawsey.qmd
          - command-line.qmd
          - best-practice-programming.qmd
      - section: "Appendices"
        contents:
          - ssh.qmd
      - acknowledgements.qmd
  
  # Footer options
  
  page-footer: 
      right:
      - icon: github
        href: https://github.com/Infectious-Disease-Modelling-UWA/2025-workshop
  
  # Appearance and misc.
  bread-crumbs: false
  page-navigation: true

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    toc: true
    code-overflow: wrap

execute:
  cache: true
  freeze: false
  
bibliography: references.bib
editor: visual
