project:
  type: website
  output-dir: docs

website:
  title: "GDM Workshop 2025"
  navbar:
    page-navigation: true
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: code-of-conduct.qmd
        text: Code of Conduct
      - about.qmd
  # sidebar:
  #   syle: "docked"
  #   search: true
  #   contents:
  #     - section: "Workshop"
  #       contents:
  #         - 
  #     - section: "Resources"
  #       contents: 
  #         - getting-started.qmd
  #         - collaborative-git.qmd
  #         - supercomputing.qmd
  #         - pawsey.qmd
  #         - best-practice-programming.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-overflow: wrap

freeze: true
bibliography: references.bib
editor: visual
