---
title: Acknowledgements
---

### Acknowledgement of country

The Kids Research Institute Australia acknowledges Aboriginal people as the Traditional Owners of the land and seas of Australia. We also acknowledge the Noongar Nation and especially the Whadjuk people as the custodians of the land on which the Institute is located.

We pay our respects to Elders past, present, and future and seek their wisdom in our work to improve the health of all children.

### Workshop material

Thank you to Lara Frcej and Victor Olet for preparing the workshop materials for Session 1 on Unix. Thank you to Victor Olet and Aurélien Cavelan for preparing the workshop materials for Session 2 on version control with Git. Thank you to Sarah Beecroft for preparing the workshop materials for Session 3 on an introduction to high performance computing. Thank you to Fathima Hassan, Sarah Beecroft, Victor Olet, Lara Frce, and Christopher Harris for supporting the preparation of the workshop.

-   The Code of Conduct is derived from work that is copyright © rOpenSci ([rOpenSci Code of Conduct](https://ropensci.org/code-of-conduct/)) made available under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/).
-   The instruction material "Setting up" is derived from work that is copyright © The Carpentries (<https://carpentries.org/>) made available under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/).
-   The instruction material "Unix Shell" is derived from work that is copyright © The Carpentries (<https://carpentries.org/>) made available under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/).
-   The instruction material "Remote logins and SSH" is derived from works that are copyright © The Carpentries (<https://carpentries.org/>) and copyright © Pawsey (<https://pawsey.atlassian.net/wiki/spaces/US/overview>) made available under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/); and copyright © GitHub, Inc. (<https://docs.github.com/en>) made available under the [CC0 1.0 Universal Deed](https://creativecommons.org/publicdomain/zero/1.0/).
-   The instruction material "Text editors: nano" is derived from work that is copyright © The Carpentries (<https://carpentries.org/>) made available under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/).
-   The instruction material "Text editors: Vim" is derived from work that is copyright © The Carpentries (<https://carpentries.org/>) made available under the [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/).