---
title: "Global Disease Modelling 2025 Workshop"
sidebar: true
---

This workshop is held 13-15 January and 22 January 2025 for the Global Disease Modelling team at The Kids Research Institute Australia, in collaboration with Pawsey Supercomputing Centre.

Participating in the workshop means you agree to abide by our [Code of Conduct](code-of-conduct.qmd).

You can access the sessions' Q&A at [slido.com](https://www.slido.com/) using the code \# 3151 5665 or by [clicking this link](https://app.sli.do/event/t1wc4szfSZLy9CzTgTEove). You can also use the Teams meeting's chat to post any questions or comments.

### Overview of sessions

-   13 Jan (Mon) at 13:00-16:00: the Unix shell.
-   14 Jan (Tue) at 13:00-16:00: version control with Git.
-   15 Jan (Wed) at 13:00-16:00: a high-level overview of high-performance computing (HPC) including logging in, modules and containers, Slurm, and job submissions.
-   22 Jan (Wed) at 13:00-16:30: a Hackathon session. We will attempt to move our individual projects to Pawsey.

### Time and location

All sessions are held in the **Small Seminar Room on Level 5** of the Perth Children's Hospital.

The first part of the workshop is held 13 to 15 January 2025 from 13:00 to 16:00 with the following schedule:

-   13:00-13:50 Workshop
-   13:50-14:00 Break
-   14:00-14:50 Workshop
-   14:50-15:15 Afternoon tea
-   15:15-16:00 Workshop

The last day of the workshop is a Hackathon held on 22 January 2025 from 13:00 to 16:30, with the following schedule:

-   13:00-14:45 Hackathon
-   14:45-15:15 Afternoon tea
-   15:15-16:30 Hackathon