---
title: SSH keys and logging in
subtitle: Fundamentals of Unix and Git
execute: 
  eval: false
number-sections: true
---

## Logging in (SSH)

::: {.callout-note title="Objectives" icon="false"}
-   Set up SSH keys for Git and Pawsey
-   Understand "where" you are
:::

1.  Check whether you already have SSH keys set up. How would you do this? You may find [Section 3](ssh.qmd#sec-sshkeys) in the Remote logins and SSH page useful.
2.  Set up your SSH key for Git. You may find [Section 3.1](ssh.qmd#sec-ssh-git) in the Remote logins and SSH page useful.
3.  Set up your SSH key for Pawsey. You may find [Section 3.2](ssh.qmd#sec-ssh-pawsey) in the Remote logins and SSH page useful.
4.  Log on to Pawsey using SSH. How do you know "where" you are? Is your terminal running on your local PC, or on Pawsey?

::: {.callout-warning title="Discussion"}
Why do you think we use the shell, or the command line, when interacting with Pawsey? Why not use a graphical user interface (GUI)?
:::

## Looking around

::: {.callout-note title="Objectives" icon="false"}
-   Navigate Pawsey using the command line
-   Understand user permissions
-   Understand the Pawsey filesystem
:::

1.  Navigate to your own software directory using `cd $MYSOFTWARE`. Now, navigate to the `GROUP` directory (also located within `pawsey1104`).
2.  Copy a folder within the `software` directory to your `scratch` directory. How would you do this?

::: {.callout-tip title="Tip" collapse="true"}
Similar to `$MYSOFTWARE`, there is an alias `$MYSCRATCH` for your scratch directory.
:::

3.  Navigate to the copied folder within your `scratch` directory.